FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY RecipeApp.sln ./
COPY RecipeApp.Api/RecipeApp.Api.csproj RecipeApp.Api/
RUN dotnet restore RecipeApp.Api/RecipeApp.Api.csproj

COPY . .
RUN dotnet publish RecipeApp.Api/RecipeApp.Api.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
EXPOSE 8080

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "RecipeApp.Api.dll"]
