import type { RecipeDetail } from "../../types/recipe";

export const mockRecipes: RecipeDetail[] = [
  {
    id: "1",
    title: "Brynt smör-pannkakor",
    slug: "brynt-smor-pannkakor",
    description: "Mjuka, gyllene pannkakor med brynt smör, kardemumma och ett friskt bärtopping.",
    category: "Breakfast",
    prepTimeMinutes: 25,
    servings: 4,
    imageUrl:
      "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=80",
    isPublished: true,
    ingredients: [
      "250 g vetemjöl",
      "2 tsk bakpulver",
      "2 msk socker",
      "350 ml mjölk",
      "2 ägg",
      "80 g brynt smör",
      "En nypa kardemumma",
    ],
    steps: [
      "Vispa ihop de torra ingredienserna i en stor skål.",
      "Blanda mjölk, ägg och brynt smör och vänd sedan ner det i de torra ingredienserna.",
      "Låt smeten vila i 10 minuter.",
      "Stek i smörad panna på medelvärme tills pannkakorna är gyllene på båda sidor.",
      "Servera med bär och en klick crème fraiche.",
    ],
  },
  {
    id: "2",
    title: "Rostad tomatpasta",
    slug: "rostad-tomatpasta",
    description: "En snabb pasta med söta rostade tomater, vitlök, basilika och olivolja.",
    category: "Dinner",
    prepTimeMinutes: 35,
    servings: 3,
    imageUrl:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=80",
    isPublished: true,
    ingredients: [
      "300 g pasta",
      "400 g körsbärstomater",
      "4 vitlöksklyftor",
      "Olivolja",
      "Färsk basilika",
      "Parmesan",
    ],
    steps: [
      "Rosta tomater och vitlök med olivolja tills de blivit mjuka och söta.",
      "Koka pastan al dente och spara lite pastavatten.",
      "Vänd ihop pasta, rostade tomater, vitlök, basilika och lite pastavatten.",
      "Toppa med parmesan och svartpeppar.",
    ],
  },
  {
    id: "3",
    title: "Citruskyckling med matig skål",
    slug: "citruskyckling-med-matig-skal",
    description: "En frisk lunchskål med örtris, ugnsstekt kyckling, avokado och citronyoghurt.",
    category: "Lunch",
    prepTimeMinutes: 30,
    servings: 2,
    imageUrl:
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
    isPublished: true,
    ingredients: [
      "2 kycklingfiléer",
      "200 g kokt ris",
      "1 avokado",
      "1 gurka",
      "Grekisk yoghurt",
      "Citronsaft",
      "Färska örter",
    ],
    steps: [
      "Krydda och ugnsstek kycklingen tills den är genomstekt.",
      "Rör ihop yoghurt med citronsaft och hackade örter.",
      "Bygg skålar med ris, skivad kyckling, avokado och gurka.",
      "Skeda över citronyoghurten före servering.",
    ],
  },
  {
    id: "4",
    title: "Mörk chokladmousse",
    slug: "mork-chokladmousse",
    description: "Djup chokladsmak, lätt konsistens och precis lagom mycket flingsalt ovanpå.",
    category: "Dessert",
    prepTimeMinutes: 20,
    servings: 6,
    imageUrl:
      "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=900&q=80",
    isPublished: true,
    ingredients: [
      "200 g mörk choklad",
      "300 ml grädde",
      "3 ägg",
      "2 msk socker",
      "Flingsalt",
    ],
    steps: [
      "Smält chokladen försiktigt och låt den svalna lite.",
      "Vispa grädden till mjuka toppar.",
      "Vispa äggulor med socker och blanda sedan med chokladen.",
      "Vänd ner den vispade grädden och låt moussen sätta sig kallt.",
      "Avsluta med en nypa flingsalt.",
    ],
  },
  {
    id: "5",
    title: "Chilistekta kikärtor",
    slug: "chilistekta-kikartor",
    description: "Krispiga ugnsrostade kikärtor med limezest, chili och rökt paprika.",
    category: "Snack",
    prepTimeMinutes: 18,
    servings: 4,
    imageUrl:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
    isPublished: true,
    ingredients: [
      "2 burkar kikärtor",
      "Olivolja",
      "1 lime",
      "Chiliflakes",
      "Rökt paprikapulver",
      "Salt",
    ],
    steps: [
      "Torka kikärtorna ordentligt och blanda med olja och kryddor.",
      "Rosta tills de är krispiga och gyllene.",
      "Avsluta med limezest och extra salt medan de fortfarande är varma.",
    ],
  },
];
