import type { RecipeDetail } from "../../types/recipe";

export const mockRecipes: RecipeDetail[] = [
  {
    id: "1",
    title: "Brynt smor-pannkakor",
    slug: "brynt-smor-pannkakor",
    description: "Mjuka, gyllene pannkakor med brynt smor, kardemumma och ett friskt bartopping.",
    category: "Breakfast",
    prepTimeMinutes: 25,
    servings: 4,
    imageUrl:
      "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=80",
    isPublished: true,
    ingredients: [
      "250 g vetemjol",
      "2 tsk bakpulver",
      "2 msk socker",
      "350 ml mjolk",
      "2 agg",
      "80 g brynt smor",
      "En nypa kardemumma",
    ],
    steps: [
      "Vispa ihop de torra ingredienserna i en stor skal.",
      "Blanda mjolk, agg och brynt smor och vand sedan ner det i de torra ingredienserna.",
      "Lat smeten vila i 10 minuter.",
      "Stek i smorad panna pa medelvarme tills pannkakorna ar gyllene pa bada sidor.",
      "Servera med bar och en klick creme fraiche.",
    ],
  },
  {
    id: "2",
    title: "Rostad tomatpasta",
    slug: "rostad-tomatpasta",
    description: "En snabb pasta med sota rostade tomater, vitlok, basilika och olivolja.",
    category: "Dinner",
    prepTimeMinutes: 35,
    servings: 3,
    imageUrl:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=80",
    isPublished: true,
    ingredients: [
      "300 g pasta",
      "400 g korszbarstomater",
      "4 vitloksklyftor",
      "Olivolja",
      "Farsk basilika",
      "Parmesan",
    ],
    steps: [
      "Rosta tomater och vitlok med olivolja tills de blivit mjuka och sota.",
      "Koka pastan al dente och spara lite pastavatten.",
      "Vand ihop pasta, rostade tomater, vitlok, basilika och lite pastavatten.",
      "Toppa med parmesan och svartpeppar.",
    ],
  },
  {
    id: "3",
    title: "Citruskyckling med matig skål",
    slug: "citruskyckling-med-matig-skal",
    description: "En frisk lunchskal med ortaris, ugnsstekt kyckling, avocado och citronyoghurt.",
    category: "Lunch",
    prepTimeMinutes: 30,
    servings: 2,
    imageUrl:
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
    isPublished: true,
    ingredients: [
      "2 kycklingfileer",
      "200 g kokt ris",
      "1 avocado",
      "1 gurka",
      "Grekisk yoghurt",
      "Citronsaft",
      "Farska orter",
    ],
    steps: [
      "Krydda och ugnsstek kycklingen tills den ar genomstekt.",
      "Ror ihop yoghurt med citronsaft och hackade orter.",
      "Bygg skalar med ris, skivad kyckling, avocado och gurka.",
      "Skeda over citronyoghurten fore servering.",
    ],
  },
  {
    id: "4",
    title: "Mork chokladmousse",
    slug: "mork-chokladmousse",
    description: "Djup chokladsmak, latt konsistens och precis lagom mycket flingsalt ovanpa.",
    category: "Dessert",
    prepTimeMinutes: 20,
    servings: 6,
    imageUrl:
      "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=900&q=80",
    isPublished: true,
    ingredients: [
      "200 g mork choklad",
      "300 ml gradde",
      "3 agg",
      "2 msk socker",
      "Flingsalt",
    ],
    steps: [
      "Smalt chokladen forsiktigt och lat den svalna lite.",
      "Vispa gradden till mjuka toppar.",
      "Vispa aggulor med socker och blanda sedan med chokladen.",
      "Vand ner den vispade gradden och lat moussen satta sig kallt.",
      "Avsluta med en nypa flingsalt.",
    ],
  },
  {
    id: "5",
    title: "Chilistekta kikartor",
    slug: "chilistekta-kikartor",
    description: "Krispiga ugnsrostade kikartor med limezest, chili och rokt paprika.",
    category: "Snack",
    prepTimeMinutes: 18,
    servings: 4,
    imageUrl:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
    isPublished: true,
    ingredients: [
      "2 burkar kikartor",
      "Olivolja",
      "1 lime",
      "Chiliflakes",
      "Rokt paprikapulver",
      "Salt",
    ],
    steps: [
      "Torka kikartorna ordentligt och blanda med olja och kryddor.",
      "Rosta tills de ar krispiga och gyllene.",
      "Avsluta med limezest och extra salt medan de fortfarande ar varma.",
    ],
  },
];
